<?xml version="1.0" encoding="UTF-8"?><testrun name="TestCalculator" project="StringCalculator" tests="10" started="10" failures="1" errors="0" ignored="0">
  <testsuite name="stringCalculator.TestCalculator" time="0.075">
    <testcase name="emptyStringReturn0" classname="stringCalculator.TestCalculator" time="0.0"/>
    <testcase name="deliminatorOfAnyLength" classname="stringCalculator.TestCalculator" time="0.0"/>
    <testcase name="addUnknownAmountOfNumber" classname="stringCalculator.TestCalculator" time="0.0"/>
    <testcase name="numberOfLengthOne" classname="stringCalculator.TestCalculator" time="0.069">
      <failure>java.lang.AssertionError: expected:&lt;4&gt; but was:&lt;3&gt;&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:834)&#13;
	at org.junit.Assert.assertEquals(Assert.java:645)&#13;
	at org.junit.Assert.assertEquals(Assert.java:631)&#13;
	at stringCalculator.TestCalculator.numberOfLengthOne(TestCalculator.java:18)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="ignoreNumberGreaterThan1000" classname="stringCalculator.TestCalculator" time="0.0"/>
    <testcase name="customexpressionShouldbeDeliminaterWithSpecialChar" classname="stringCalculator.TestCalculator" time="0.0"/>
    <testcase name="customDeliminator" classname="stringCalculator.TestCalculator" time="0.0"/>
    <testcase name="handleNewLinebetweenNumber" classname="stringCalculator.TestCalculator" time="0.003"/>
    <testcase name="negativeNumberException" classname="stringCalculator.TestCalculator" time="0.002"/>
    <testcase name="sumOfNumberSeperatedByComma" classname="stringCalculator.TestCalculator" time="0.001"/>
  </testsuite>
</testrun>
